services:
  redis:
    container_name: redis
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - contador_network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - contador_network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - contador_network
volumes:
  redis_data:
networks:
  contador_network:
    driver: bridge
