apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: super-contador
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081    # optional: specify the external port (30000-32767 range)
