apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: super-contador
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080    # optional: specify the external port (30000-32767 range)
