apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: super-contador
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi            # adjust to your needs
